# Generated by Django 4.1.2 on 2022-11-03 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название роли')),
                ('priority', models.IntegerField(choices=[('C', 1), ('B', 2), ('I', 3)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(help_text='Введите номер телефона', max_length=12, verbose_name='Номер телефона')),
                ('token_code', models.CharField(help_text='Генерируется автоматически', max_length=255, verbose_name='Ваш токен')),
                ('age', models.IntegerField(help_text='Введите возраст (18-60)', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)], verbose_name='Возраст')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
