# Generated by Django 4.1.2 on 2022-11-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='call_number',
            field=models.CharField(error_messages='Номер не должен превышать длину в 12 символов', help_text='Введите номер телефона', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
