# Generated by Django 4.1.2 on 2022-11-03 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_profile_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='call_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=12, validators=[django.core.validators.MaxLengthValidator(12, message={'cull_number': 'Номер не должен превышать длину в 12 символов'})], verbose_name='Номер телефона'),
        ),
    ]
