# Generated by Django 4.1.2 on 2022-11-03 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_profile_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(help_text='Введите возраст (18-60)', validators=[django.core.validators.MinValueValidator(18, message='число не должно быть меньше 18'), django.core.validators.MaxValueValidator(60, message='Число не должно превышать 60')], verbose_name='Возраст'),
        ),
    ]
