# Generated by Django 4.1.2 on 2022-11-04 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Procunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Количество товара не должно быть меньше 0')], verbose_name='Количество товара')),
                ('unit', models.CharField(choices=[('gr', 'Грамм'), ('kg', 'Килограмм'), ('ob', 'Штук'), ('st', 'Упоковок')], max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leveone.category', verbose_name='Категория товара')),
            ],
        ),
    ]
