# Generated by Django 4.1.2 on 2022-11-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leveone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procunt',
            new_name='Product',
        ),
    ]
